version: "3"
services:
  parser:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: parser
    volumes:
      - ../configs/.env-parser:/opt/app/.env
      - ../db/db.json:/opt/app/db/db.json
      - ../db/stopwords.json:/opt/app/db/stopwords.json
      - ../db/parsingStatus.json:/opt/app/db/parsingStatus.json
    ports:
      - 3000:3000
networks:
  myNetwork:
    driver: bridge
